### Get all users
GET http://localhost:8080/users

### Get user by ID
GET http://localhost:8080/users/2


### Create new user
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "password": "Password123"
}

### Update user by ID
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@example.com"
}

### Delete user by ID
DELETE http://localhost:8080/users/3





### Get all attendances
GET http://localhost:8080/api/attendances  

### Get attendance by ID
GET http://localhost:8080/api/attendances/1

### Create new attendance (Pedding)
POST http://localhost:8080/api/attendances
Content-Type: application/json

{
  "userId": 2,
  "checkInTime": "2025-08-19T09:00:00"
}

### Update attendance by ID (Pedding)
PUT http://localhost:8080/api/attendances/1
Content-Type: application/json

{
  "userId": 1,
  "date": "2025-08-18",
  "status": "absent"
}

### Delete attendance by ID
DELETE http://localhost:8080/api/attendances/4


### GET all student
GET http://localhost:8080/api/students

### Get student by ID
GET http://localhost:8080/api/students/1

## Create new student
POST http://localhost:8080/api/students
Content-Type: application/json

{
  "name": "John Doe",
  "age": 20,
  "studentClass": "10th Grade"
}
